WDUSR2PTT_src=wdusr2ptt.c
WDUSR2PTT_include=wdusr2ptt.h
wdusr2ptt: $(WDUSR2PTT_src) $(WDUSR2PTT_include)
	$(CC) -I./ $(WDUSR2PTT_src) -o $@
WDDIR2PTT_src=wddir2ptt.c
WDDIR2PTT_include=wddir2ptt.h
wddir2ptt: $(WDDIR2PTT_src) $(WDDIR2PTT_include)
	$(CC) -I./ $(WDDIR2PTT_src) -o $@
